name: Check and Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  JAVA_VERSION: '11'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Gradle Stuff
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Unit Tests & Style Checks
      - name: Run Checks (JUnit, Checkstyle, SpotBugs)
        run: ./gradlew --continue check

      - name: Publish JUnit Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Checkstyle Report
        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        if: always()
        with:
          path: 'build/reports/checkstyle/*.xml'

      - name: Publish SpotBugs Report
        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
        if: always()
        with:
          path: 'build/reports/spotbugs/*.xml'
