name: Check and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Run Checks (JUnit, Checkstyle, SpotBugs)
        run: ./gradlew --continue check

      - name: Publish JUnit Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Publish Checkstyle Report
        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        if: always()
        with:
          path: 'build/reports/checkstyle/*.xml'

      - name: Publish SpotBugs Report
        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
        if: always()
        with:
          path: 'build/reports/spotbugs/*.xml'
